/*
 * Copyright 2015 University of Basel, Graphics and Vision Research Group
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * =====================================================================================
 *
 *       Filename:  Metropolis.h
 *
 *    Description:  Implementation of the Metropolis Hastings Algorithm
 *
 *        Version:  1.0
 *        Created:  13.04.2010 15:58:30
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Sandro Schönborn (ses), sandro.schoenborn@unibas.ch
 *        Company:  University of Basel
 *
 * =====================================================================================
 */


#ifndef  Metropolis_INC
#define  Metropolis_INC

#include "../MarkovChain.h"
#include "../RandomGenerator.h"

namespace sampling
{

  /* \brief Implementation of a Metropolis Markov Chain Sampler (no transition corrections)
   *
   * Proposals are generated by the ProposalGenerator<T> and are evaluated
   * by the DistributionEvaluator<T> -- Attention: Needs LOG Probability values!! */
  template <typename T>
  class Metropolis : public MarkovChain<T>
  {
    public:
      typedef T SampleType;

    public:
      typedef ProposalGenerator<T> Generator;
      typedef DistributionEvaluator<T> Evaluator;
      typedef ChainLogger<T> Logger;

    public:
      /** \brief Init Chain, Use a predefined Generator with seed */
      Metropolis( Generator* propgen, Evaluator* disteval, Logger* chainlogger, const T& initsample, RandomGenerator* engine ) :
        currentSample( initsample ),
        pGenerator( propgen ),
        pEvaluator( disteval ),
        pLogger( chainlogger),
        rndEngine( engine )
      {
        currentProbVal = pEvaluator->evalSample( currentSample );
        pLogger->notifyReset( currentSample, currentProbVal, pGenerator, pEvaluator );
      }

      virtual ~Metropolis() {}

      virtual void current( SampleType& rSample ) const
      {
        rSample = currentSample;
      }

      virtual double currentValue() const
      {
        return currentProbVal;
      }

      double setState( const SampleType& newState )
      {
        currentSample = newState;
        currentProbVal = pEvaluator->evalSample( currentSample );
        pLogger->notifyReset( currentSample, currentProbVal, pGenerator, pEvaluator );
        return currentProbVal;
      }
      /** Get next sample: in Metropolis-Hastings manner: propose new, accept with
      *   probability P=min(1, P(new)/P(old) * &ans(new->old)/&ans(old->new))
      */
      virtual void next( SampleType& rNextSample )
      {
        // generate a Proposal
        pGenerator->generateProposal( rNextSample, currentSample );

        // Evaluate Proposal
        double probVal = pEvaluator->evalSample( rNextSample );

        // log Probability acceptance prob
        double acceptVal = std::min<double>( 1.0, std::exp( probVal - currentProbVal ) );

        // Decide whether to accept or reject it
        double rndVal = rndEngine->uniformDbl();
        if ( rndVal <= acceptVal && probVal == probVal )
        {
          //accept
          currentSample = rNextSample;
          currentProbVal = probVal;
          pLogger->notifyAccept( rNextSample, probVal, pGenerator, pEvaluator );
        }
        else
        {
          pLogger->notifyReject( rNextSample, probVal, pGenerator, pEvaluator );
          rNextSample = currentSample; // keep current state
          //reject - do nothing
        }
      }

    private:
      SampleType currentSample;
      double currentProbVal;

      Generator* pGenerator;
      Evaluator* pEvaluator;
      Logger* pLogger;

    private:
      RandomGenerator* rndEngine;
  };
}

#endif   /* ----- #ifndef Metropolis_INC  ----- */
